### ISSUE TITLE
Represent mutable shared flow as a read-only shared flow in FlowEventHub

### ISSUE THREAD

**Issue by Maksim2355** [surfstudio/surf-mvi-flow#23]
Сейчас, в FlowEventHub у нас нет каста для mutableSharedFlow к обычному sharedFlow

```kotlin

 override fun observe(): Flow<T> {
        return hubFlow
    }

```

Я немного новенький, но получается таким образом мы можем взять шину и привести ее к мутбельному виду, чтобы что-то заэмитить?

```kotlin

(hub.observe() as MutableSharedFlow).emit(...)

```

не стоит ли этот метод изменить следующим образом

```kotlin

 override fun observe(): Flow<T> {
        return hubFlow.asSharedFlow()
    }

```

**Comment by margarita-v** [comment]
но ведь в самом FlowEventHub есть метод emit, или проблема в другом заключается?

**Comment by Maksim2355** [comment]
Да минорная проблемка, мы передаем Flow<T>, который можно скастить к MutableSharedFlow из любого участка кода, где нам это не надо делать

**Comment by margarita-v** [comment]
Хорошая идея, поправим 👍
